name: cd

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
env:
  TF_VAR_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_VAR_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  PLAN_OUTPUT: tfplan

jobs:
  terraform:
    name: Terraform CD
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: 1.0.0

    - name: Terraform format
      run: terraform fmt -recursive -check

    - name: Terraform init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan -out $PLAN_OUTPUT

    - name: Terraform apply
      run: terraform apply -auto-approve $PLAN_OUTPUT
